import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Innovate Next",
  description: "Generated by create next.js. This task from Innovate International LTD ",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased `}>
        <main className="max-w-[1441px] w-full mx-auto p-2 md:p-0 bg-white">
          <div className="min-h-screen">{children}</div>
        </main>
      </body>
    </html>
  );
}
